name: Deploy Next.js application
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      #   - name: Run linting
      #     run: npm run lint

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: jdmghk/kmc-frontend:latest
          target: runner
          build-args: |
            BASE_URL=${{ secrets.BASE_URL }}

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull latest image
        run: docker pull jdmghk/kmc-frontend:latest

      - name: Check if Container Exists and Stop it
        run: |
          if [ "$(docker ps -aq -f name=kmc-frontend-container)" ]; then
            docker rm -f kmc-frontend-container
          fi

      - name: Run new container
        run: |
          docker run -d \
            --init \
            -p 3000:3000 \
            --name kmc-frontend-container \
            -e BASE_URL="${{ secrets.BASE_URL }}" \
            jdmghk/kmc-frontend:latest

      - name: Check container logs
        run: |
          sleep 10 # Wait for the container to start up
          docker logs kmc-frontend-container

      - name: Clean up Docker resources
        run: |
          # Remove unused containers
          docker container prune -f
          # Remove unused images
          docker image prune -a -f
          # Remove unused volumes
          docker volume prune -f
          # Remove unused networks
          docker network prune -f
